### ISSUE TITLE
snap.opengrok.index-sync-daemon.service failed

### ISSUE THREAD

**Issue by Yaaaaao** [kubiko/opengrok-snap#3] opened 2021-06-01 12:25 UTC
Hi kubiko,

I just setup an OpenGrok instance on ubuntu-18.04 and it works perfectly. A big thanks to you!
However I found index-sync failaure from journal. May I ask if you had hint the same problem?

Best Regard
Yao

> May 28 00:38:05 ubuntu systemd[1]: Started Service for snap application opengrok.index-sync-daemon.
> May 28 00:38:09 ubuntu opengrok.index-sync-daemon[14641]: RESTful command {'command': ['http://localhost:8080/source/api/v1/messages', 'POST', {'cssClass': 'info', 'duration': 'PT1H', 'tags': ['%PROJECT%'], 'text': 'resync + reindex in progress'}]} failed: 400 Client Error:  for url: http://localhost:8080/source/api/v1/messages
> May 28 00:38:09 ubuntu opengrok.index-sync-daemon[14641]: processing of project 'AOSP' failed
> May 28 00:38:09 ubuntu opengrok.index-sync-daemon[14641]:   failed commands:
> May 28 00:38:09 ubuntu opengrok.index-sync-daemon[14641]:     '{'command': ['http://localhost:8080/source/api/v1/messages', 'POST', {'cssClass': 'info', 'duration': 'PT1H', 'tags': ['%PROJECT%'], 'text': 'resync + reindex in progress'}]}': 1
> May 28 00:38:10 ubuntu systemd[1]: snap.opengrok.index-sync-daemon.service: Main process exited, code=exited, status=1/FAILURE
> May 28 00:38:10 ubuntu systemd[1]: snap.opengrok.index-sync-daemon.service: Failed with result 'exit-code'.

**Comment by kubiko** [comment] 2022-02-04 21:58
Hi @Yaaaaao
Sorry for delay, as this is just my pet project.
This has been now fixed.
For context, this was caused by undocumented change in REST API, when even now OpenGrok own examples are using wrong name, `cssClass` vs `messageLevel`
Fix commit is here: [922aa198cc710e8bca7c2cb7356a2204fb6f2a7e](https://github.com/kubiko/opengrok-snap/commit/922aa198cc710e8bca7c2cb7356a2204fb6f2a7e)

**Closed as completed** 2022-02-04 21:58 UTC

**Comment by anhtn512** [comment] 2022-03-26 14:31
Hi @Yaaaaao,
I just setup an OpenGrok instance on ubuntu-18.04 and got an issue like photo bellow
can you show me how you debloy opengrok
![image](https://user-images.githubusercontent.com/24378573/160244113-b539e769-00bb-4be9-8b6b-dac9c62ec055.png)

**Comment by Yaaaaao** [comment] 2022-03-26 14:58
Hi @kubiko, Thank you for the fix! I will take a try next week.

**Comment by Yaaaaao** [comment] 2022-03-26 15:06
Hi @anhtn512 

You need to put the source code at `${SNAP_COMMON}/src` and run the indexer `sudo opengrok.indexer`. It will generate configuration file.

You might want to take a look at https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step2---deploy-the-web-application
>After the initial startup (i.e. before the indexer is run for the first time) the web application will display an error saying that it cannot read the configuration file. This is expected since the configuration file is yet to be generated by the indexer.
